### ISSUE TITLE
Call subquery variable scope clause

### ISSUE THREAD

**Issue by nk-coding** [neo4j/cypher-dsl#1062]
Hi,
I want to kindly ask if it would be possible to add support for the call subquery variable scope clause.
I would really like to get rid of the deprecation warnings caused by the deprecated importing WITH clause.
I hope I didn't overlook already existing support, I had a look at the docs and source code, but I did not find anything.

**Comment by michael-simons** [comment]
I am gonna add a dedicated Dialect for 5.23. I can't sensible add anything to the builder interface here.

**Comment by nk-coding** [comment]
Thx a lot
Using a dialect is also the solution I would have preferred
