### ISSUE TITLE
LabelExpression support

### ISSUE THREAD

**Issue by ikwattro** [neo4j/cypher-dsl#1077]
Hi, 

Lot of our future query generation plans will need to support [label expressions](https://neo4j.com/docs/cypher-manual/current/clauses/match/#label-expression-match-or-expression), such as : 

```
MATCH (n:Person|Organization)

MATCH (n:(Person|Organization)&!Sanctioned)
```

I couldn't find this possible yet with the cypher-dsl, I would love to see this feature happen <3

**Comment by michael-simons** [comment]
We already support rendering them via `LabelExpression`, but you are right, there is no builder yet.

**Comment by michael-simons** [comment]
I am getting old: https://github.com/neo4j/cypher-dsl/blob/main/neo4j-cypher-dsl/src/test/java/org/neo4j/cypherdsl/core/LabelExpressionTest.java#L39 

It is there already.

**Comment by ikwattro** [comment]
Thanks @michael-simons !
