### ISSUE TITLE
Each alias occurrence introduces new generated names, even if the alias is the same.

### ISSUE THREAD

**Issue by Andy2003** [neo4j/cypher-dsl#1084]
I try to compare the following queries by parsing them to cypherdsl and rendering again

Query 1:

```cypher
MATCH (this:Film:Multimedia)
CALL {
	WITH this
	MATCH (this_actors:Actor:Person)-[this0:ACTED_IN]->(this)
	WITH this_actors {
		.name
	} AS this_actors
	RETURN collect(this_actors) AS this_actors
}
RETURN this {
	.title,
	actors: this_actors
} AS this
```

Query 2:

```cypher
MATCH (this:Film:Multimedia)
CALL {
	WITH this
	MATCH (actor0:Actor:Person)-[actedIn0:ACTED_IN]->(this)
	WITH actor0 {
		.name
	} AS actors
	RETURN collect(actors) AS actors
}
RETURN this {
	.title,
	actors: actors
} AS this
```

The normalized queries are:

Normalized query 1:

```cypher
MATCH (v0:Film:Multimedia)
CALL {
  WITH v0
  MATCH (v1:Actor:Person)-[v2:ACTED_IN]->(v0)
  WITH v1 {
    .name
  } AS v3
  RETURN collect(v3) AS v4
}
RETURN v0 {
  .title,
  actors: v4
} AS v1
```

Normalized query 2:

```cypher
MATCH (v0:Film:Multimedia)
CALL {
  WITH v0
  MATCH (v1:Actor:Person)-[v2:ACTED_IN]->(v0)
  WITH v1 {
    .name
  } AS v3
  RETURN collect(v3) AS v4
}
RETURN v0 {
  .title,
  actors: v4
} AS v3
```

Here is a diff view of everything:

![image](https://github.com/user-attachments/assets/ce265bcd-31c2-474f-96ba-a4ccbd9c9a41)

As you can see for query 1 the result alias is `v1` (which  is not an error itself), but the semantically equally query 2 parses to a different result alias `v3`. 

To normalize the queries I use the following code:

```kotlin
val renderer = Renderer.getRenderer(Configuration.newConfig()
    .withPrettyPrint(true)
    .withGeneratedNames(true)
    .build())

renderer.render(CypherParser.parse(cypher, Options.newOptions()
    .createSortedMaps(true)
    .alwaysCreateRelationshipsLTR(true)
    .build()))
```

**Comment by michael-simons** [comment]
I won't be able to fix this I am afraid, without breaking tons of other things.

**Comment by michael-simons** [comment]
Please have a look at the last PR added to this branch… https://github.com/neo4j/cypher-dsl/tree/issue/does-itscope and test your thing with it. It fixes stuff, to truly keep queries semantically equal (reusing aliases, too). Please note that the queries above *won't* normalize the same as the former uses `this_actors` 3 times, but `actors` only 2 times. I can only track the aliases introduced, I am not doing a full semantic analysis here (and I won't).

See which tests I needed to touch, essentially all that uses `this` as a symbolic name at the start of the match and overwrite it with `this {.something} as this` in the end.

Stuff hunted me in my dreams last night, pls refrain from more issues today, need to get some rest ;)
