### ISSUE TITLE
hasLabels equivalent for LabelExpression

### ISSUE THREAD

**Issue by nk-coding** [neo4j/cypher-dsl#1141]
Hi,
another small feature request:
A `Node.hasLabels` equivalent for `LabelExpression`.
I hope I did not overlook it.
And I know I could implement one by myself, but I think having this feature here would also be nice for others.

**Comment by michael-simons** [comment]
Thanks for the nice suggestion. Implemented and released. Happy Christmas.

**Comment by nk-coding** [comment]
Thanks for adding the idea. And Happy Christmas, too
